import { GoogleGenAI } from "@google/genai";

const genAI = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY || "" });

export const geminiService = {
  async generateImage(prompt: string, referenceImages: string[]) {
    const model = "gemini-2.5-flash-image"; // As requested
    
    const parts: any[] = referenceImages.map(base64 => ({
      inlineData: {
        data: base64.split(',')[1],
        mimeType: "image/png"
      }
    }));

    parts.push({ text: prompt });

    const response = await genAI.models.generateContent({
      model: model,
      contents: { parts },
    });

    for (const part of response.candidates?.[0]?.content?.parts || []) {
      if (part.inlineData) {
        return `data:image/png;base64,${part.inlineData.data}`;
      }
    }
    
    throw new Error("No image generated by the model.");
  }
};
